### ISSUE TITLE
Request for animated example 

### ISSUE THREAD

**Issue by beckylum0216** [nem0/OpenFBX#73]
Hi,

I would like to request that a comprehensive animation loading example be made available for loading animations. Following issue #71, attempts have been made to follow the Lumix engine example. Unfortunately, the lack of documentation has made loading fba animation files impossible. Documentation from FBXSDK did not help in this issue as openFBX != FBXSDK. The main issue for me is the loading of bones, animation bone offsets, frames and animated transforms. It would be appreciated if there was documentation on what type of animation openfbx is supporting and also provide either a doxygen or inline comments for the lumix engine's import example. 

Thanks.

**Comment by nem0** [comment]
Hi, writing an example for loading animations (or just loading and rendering a static mesh) is relatively long task and that's why demo for OpenFBX is just simple data viewer. I understand that it's hard without any documentation or samples but I am sorry, I don't plan to write any samples or demos other than what's in Lumix Engine. I will try to ask other ofbx users, if they have any simple example and let you know, if I find anything.

OpenFBX supports skeletal animation (Object::Type ANIMATION_STACK, ANIMATION_LAYER, ANIMATION_CURVE and ANIMATION_CURVE_NODE) and blend shapes were added by another contributor (Object::Type BLEND_SHAPE and BLEND_SHAPE_CHANNEL)
